### ISSUE TITLE
Recording Oracle - Exchange Oracle - Notify Exchange Oracle about invalid answers

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#1003]
**Description**
In case the Recording Oracle detects an invalid answer, it needs to notify it to the Exchange Oracle to keep gathering for new answers

https://tech-docs.humanprotocol.org/architecture/exchange-oracle#webhook

**Comment by simulacrum6** [comment]
Is there a payload specification for this? I'd assume it would look something like this:

```typescript
{
  chainId: number
  escrowAddress: string
  dataPoints: string[] // task_keys or datapoint_uris
}
```

**Comment by portuu3** [comment]
> Is there a payload specification for this? I'd assume it would look something like this:
> 
> ```ts
> {
>   chainId: number
>   escrowAddress: string
>   dataPoints: string[] // task_keys or datapoint_uris
> }
> ```

Check the updated docs for exchange oracle: https://tech-docs.humanprotocol.org/architecture/exchange-oracle#webhook
