### ISSUE TITLE
Reputation Oracle - Add user type

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#1041]
**Description**
Add user type in sign up for different type of users:
- Workers
- Job Launcher
- Exchange Oracle
- Recording Oracle
- Reputation Oracle

**Motivation**
Need to distinguish between all different type of users.

**Implementation details** 
- Add a migration to save userType in database
- Add a parameter to the endpoint for userType
- Tests

**Comment by leric7** [comment]
Done by @flopez7

**Comment by portuu3** [comment]
Done in #895
