### ISSUE TITLE
Job Launcher Client - Keep logged in and backend returns unauthorized

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#1080]
**Describe the bug**
It keeps as logged in but the backend is returning unauthorized.

**Expected behavior**
Should log me out

**Screenshots**
![image](https://github.com/humanprotocol/human-protocol/assets/61605646/b38734ea-2c3b-439d-b7a2-3a04d4a18b5e)

**Comment by ansaqib** [comment]
Closed with [1105](https://github.com/humanprotocol/human-protocol/pull/1105)
