### ISSUE TITLE
Contracts - Complete escrow

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#1107]
**Description**
At this moment to set the escrow as COMPLETE, we need to do an extra call to the contract just to set the status, which means an extra cost in fees:
```
function complete() external override notExpired trustedOrReputationOracle {
        require(status == EscrowStatuses.Paid, 'Escrow not in Paid state');
        status = EscrowStatuses.Complete;
        emit Completed();
}
```
The condition to be completed is that status needs to be PAID.
Now, the escrow is only set as PAID in the bulkPayout function when the balance is equal to 0.
```
bool isPartial;
if (balance == 0) {
    status = EscrowStatuses.Paid;
    isPartial = false;
} else {
    status = EscrowStatuses.Partial;
    isPartial = true;
}
```

We should remove PAID status and set it to COMPLETE when the balance is 0.

We might have a situation where residual token amounts are left over after payouts, where the balance is not zero, the solution for this is setting a minimum residual amount, below which tokens would automatically be sent to the job launcher.

**Motivation**
Reduce number of transactions and cost.

**Implementation details** 

- If balance is 0 complete the escrow.
- If balance is <= 10 WEI of the fund token, send this residual amount to Job Launcher and complete the escrow.
- Remove PAID status.

**Comment by posix4e** [comment]
Does this handle the 1 day delay for abuse?
