### ISSUE TITLE
Exchange Oracle - Abuse detection

### ISSUE THREAD

**Issue by posix4e** [humanprotocol/human-protocol#113]
**Description**
When workers are solving jobs they need to have an option to notify abusive content. This notification should be send to a slack channel.

**Motivation**
Detect abusive content like bad words, porn, etc.

**Implementation details** 
Create an endpoint that receives the notification from the user and send the information to Slack, then in Slack we should be able to Stop or Continue with the job. (https://api.slack.com/messaging/attachments-to-blocks)
The endpoint body should be something like:
{
  escrowAddress,
  reason
}

Also the solving process should be paused.

**Comment by portuu3** [comment]
@posix4e is this about fortune?

**Comment by posix4e** [comment]
Everything should support this
