### ISSUE TITLE
Fortune: Replace Number with BigInt in reputation-oracle/index.js

### ISSUE THREAD

**Issue by Dzeranov** [humanprotocol/human-protocol#129]
**Problem:**
If you use a big funding amount, on a `bulkPayout` step there will be an error due to the incorrect number representation (`5e+21` for example)

**Location:**
reputation-oracle/index.js

**Steps to reproduce:**
1. Create an escrow
2. Fund it with 10000 HMT
3. Setup escrow and send fortunes.
4. Once final fortune is received there will be an error.

**How to fix:**
Replace Number with BigInt
`const balance = Number(await Escrow.methods.getBalance().call({ from: account.address }));`

**Comment by portuu3** [comment]
it should be fixed with new SDK that uses BigNumber
