### ISSUE TITLE
Fortune: Reputation Network 

### ISSUE THREAD

**Issue by vkomodey** [humanprotocol/human-protocol#131]
Example of the reputation network. Store addresses and their reputations in the Blockchain or inside the reputation oracle's process.

Worker payouts should be adjusted based on the reputation score.
https://github.com/humanprotocol/fortune/blob/master/examples/reputation-oracle/index.js#L44

Each worker has his own reputation score - a number from 0 to 1 which has correlation on the reward that is given to this particular address

In case of “correct” work(from the rep oracle perspective), each worker should be rewarded with the appropriate amount of tokens and his priority should be increased

For the payout, it could be the formula: total reward = SUM(reputation_score * n * x), where n - is an amount of task being made by one worker, x - is some reward variable that needs to be found

Reputation Scores should be adjustable values. For the correct work reputation score goes higher, for not correct it goes down

**Comment by portuu3** [comment]
done in #155
