### ISSUE TITLE
Chatbot - Milestone 2

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#1360]
Base on [Milestone 1](https://github.com/humanprotocol/human-protocol/issues/948), Milestone 2 should have the following functionalities:

1. Set a unique API key in the environment variables file. There was a mistake in Milestone 1, the api key should not be set by user, it should unique for all users and set by the bot owner as environment variable.
2. Create chatbot roles. The roles Launcher and Viewer(default).
3. SetRole command. This command is only allowed for chatbot owners.
4. RemoveRole command. This command is only allowed for chatbot owners.
5. List pending jobs. https://job-launcher-server-humanprotocol.vercel.app/swagger#/Job/JobController_getJobList
6. The bot should return the results privately to the user who requested them.
7. Use subgraph for tracking escrows to avoid overloading backend. Use this SDK function [get_escrows](https://sdk.humanprotocol.org/python-sdk/human_protocol_sdk.escrow/human_protocol_sdk.escrow.escrow_utils#static-get_escrows-filter-less-than-human_protocol_sdk.filter.escrowfilter-object-greater-than). For this the bot will need to get the escrow address using get details [endpoint](https://job-launcher-server-humanprotocol.vercel.app/swagger#/Job/JobController_getDetails), have in mind that the escrow address is not available until the escrow has been created on chain (around 10min max)

**Comment by sarthakvijayvergiya** [comment]
I've started working on it!
@portuu3 Could you please assign the task to me?

**Comment by portuu3** [comment]
> I've started working on it! @portuu3 Could you please assign the task to me?

done!

**Comment by sarthakvijayvergiya** [comment]
Adding the pull request link here!!

https://github.com/sarthakvijayvergiya/humanprotocol-discord-bot/pull/5
