### ISSUE TITLE
Become the official HMT Elrond maintainer

### ISSUE THREAD

**Issue by Human-Protocol** [humanprotocol/human-protocol#138]
HMT-Escrow supports arbitrary networks but there's a bit of work to do to make a network first class and make sure that it works. You can gain a yearly bonus by being our network sponsor. If you need support please join tech-discussions on the HUMAN Protocol discord linked on hmt.ai. 

### Steps to receive gitcoin bounty
- [ ] Suggest and have us authorize your bridging strategy. After all we need to bridge HMT over to the new network. Usually we need to use a erc20 compatible approach.
- [ ] The contracts on the Elrond devnet have already been launched, please make sure that everything is working
- [ ] Launch contracts on production network and file a commit with all the contract information to this repo's documentation. Here's an example https://github.com/humanprotocol/hmt-escrow/pull/296
* [ ] Implement eth-kvstore in Rust and launch on Elrond testnet https://github.com/humanprotocol/eth-kvstore
- [ ] Add the contracts to the relevant network scanner (etherscan equivalent) 
- [ ] Add to human dashboard [ https://dashboard.humanprotocol.org/ ]. This will require that you configure a human subgraph
- [ ] Request to become the maintainer for Elrond. We will list you on our repo, give you an extra reward (generally around 1 ETH per year) and invite you to conferences. We will celebrate your name forever!
- [ ] Verify bridging of tokens works
### High level rules to make sure that you are doing this correctly
- [ ] We never want to create a mintable token. Your change should not change the total token supply from 1 billion
- [ ] When deploying production contracts use a dedicated wallet with a seed phrase you don't use anywhere else. You might be required to share it with us.

**Comment by vladNed** [comment]
I was waiting review from the staff on the contracts and dapp implementation. Will resume activity once I get a go-ahead from the team
