### ISSUE TITLE
Get a skale maintainer and verify all the steps have been done

### ISSUE THREAD

**Issue by posix4e** [humanprotocol/human-protocol#139]
The skale implementation has already had a good deal of work done for it

https://github.com/humanprotocol/hmt-escrow/pull/261
https://github.com/humanprotocol/hmt-escrow/commit/5357df3e81a0296db68b666d73d4b957efbfaca8

So please build on top of this.

HMT-Escrow supports arbitrary EVM networks but there's a bit of work to do to make a network first class and make sure that it works. All of our EVM network launches are supported by gitcoin but you can gain a yearly bonus by being our network sponsor. 

### Steps to receive gitcoin bounty
* [ ] Launch the contracts on the devnet and make sure that everything is working
* [ ] Launch contracts on production network and file a commit with all the contract information to this repo's documentation. Here's an example https://github.com/humanprotocol/hmt-escrow/pull/296
* [ ] Launch KVstore contracts https://github.com/humanprotocol/eth-kvstore
* [ ] Add the contracts to the relevant network scanner (etherscan equivalent) 
* [ ] Launch a working app on the network. The easiest one to get going is our example fortune. https://github.com/humanprotocol/fortune  Make a video of the functionality of the app working on the new network and link to relevant scanner transactions.
* [ ] Add to human dashboard [ https://dashboard.humanprotocol.org/ ]
* [ ] Request to become the maintainer for your EVM network. We will list you on our repo, give you an extra reward (generally around 1 ETH per year) and invite you to conferences. We will celebrate your name forever!
* [ ] Verify bridging of tokens works
### High level rules to make sure that you are doing this correctly
* [ ] We never want to create a mintable token. Your change should not change the total token supply from 1 billion

**Comment by foufrix** [comment]
Hi @AzizBardi, happy new year! Do you have news on the skale mainnet deployment?

**Comment by AzizBardi** [comment]
Hi @foufrix happy new year ! :D 
Skale team is having meeting woth Human Protocol but normally i will update you for the last implementation of the main net.

**Comment by AzizBardi** [comment]
Hello,
So I just made a pull request and as I saw it was approved,
https://github.com/humanprotocol/hmt-escrow/pull/451
I wanted to ask if there is anything missing, or if I need to do something else.
everything is done except for the graph node I will soon give you an update.

**Comment by AzizBardi** [comment]
Hello,
bridge is working Eth->Europa->Human chain

Tx send HMT token on Ethereum:
https://etherscan.io/tx/0xbfba286e80e03264f08a21a9f1d5a74cf592d55221eaa0d05df4b842277d364d

Tx receive HMT token on Europa chain:
https://elated-tan-skat.explorer.mainnet.skalenodes.com/tx/0x7c385c3cc8030876757ca0727d1b2c6ed9471c9a0036f8de379e46c2cbd6ca67/token-transfers

Tx send HMT token on Europa chain:
https://elated-tan-skat.explorer.mainnet.skalenodes.com/tx/0x5b1799a532ed21010afc38ba4bbefebc574d4de87a434d054ee148204e73568c/token-transfers

Tx receive HMT token on Human-Protocol chain:
https://wan-red-ain.explorer.mainnet.skalenodes.com/tx/0x0b516ec1ad438d2ac28c0924ff7e075b4d93968c762410a642b74042c9f51a85/token-transfers

**Comment by foufrix** [comment]
Hi @AzizBardi thank you for your contribution,

Can you send all those information like this comment: https://github.com/humanprotocol/hmt-escrow/issues/335

So that it can be reviewed easily by the human protocol team?

**Comment by AzizBardi** [comment]
> Hi @AzizBardi thank you for your contribution,
> 
> Can you send all those information like this comment: https://github.com/humanprotocol/hmt-escrow/issues/335
> 
> So that it can be reviewed easily by the human protocol team? 

Sure thing !

**Comment by AzizBardi** [comment]
Hello, 
All steps have been done, please find below the necessary informations.

- [ done] Launch the contracts on the devnet and make sure that everything is
working
- [ done] Launch contracts on the production network and file a commit with all
the contract information to this repo's documentation. Here's an example
https://github.com/humanprotocol/hmt-escrow/pull/296
- [done ] Launch KVstore contracts https://github.com/humanprotocol/ethkvstore
- [done ] Add the contracts to the relevant network scanner (etherscan
equivalent)
4 tasks are done, please check the pull request:
 https://github.com/humanprotocol/hmt-escrow/pull/451
- [done ] Launch a working app on the network. The easiest one to get going is
our example fortune. https://github.com/humanprotocol/fortune Make a video of
the functionality of the app working on the new network and link to relevant
scanner transactions.
this is a video about the fortune app running on skale network (final staging
test before mainnet) with skale hmt token.
you can check the transactions on this link :
https://staging-perfect-parallel-gacrux.explorer.staging-v3.skalenodes.com/
address/0x635197501e5a85eC13a17c9c500cFdB32EC32d2f/transactions
this is the address and the skale network i am using :
URL: https://staging-v3.skalenodes.com/v1/staging-perfect-parallel-gacrux
HMT Token on Goerli: 0xd3A31D57FDD790725d0F6B78095F62E8CD4ab317
HMT Token on schain: 0x635197501e5a85eC13a17c9c500cFdB32EC32d2f
this is the video for further informations:
[Uploading fortuneappskalenetwork.zip…]()
- [ done] Add to human dashboard [ https://dashboard.humanprotocol.org/ ]
- [ done] Request to become the maintainer for your EVM network. We will list
you on our repo, give you an extra reward (generally around 1 ETH per year)
and invite you to conferences. We will celebrate your name forever!
- [ done] Verify bridging of tokens works
bridge is working Eth->Europa->Human chain
Tx send HMT token on Ethereum:
https://etherscan.io/tx/
0xbfba286e80e03264f08a21a9f1d5a74cf592d55221eaa0d05df4b842277d36
4d
Tx receive HMT token on Europa chain:
https://elated-tan-skat.explorer.mainnet.skalenodes.com/tx/
0x7c385c3cc8030876757ca0727d1b2c6ed9471c9a0036f8de379e46c2cbd6c
a67/token-transfers
Tx send HMT token on Europa chain:
https://elated-tan-skat.explorer.mainnet.skalenodes.com/tx/
0x5b1799a532ed21010afc38ba4bbefebc574d4de87a434d054ee148204e7356
8c/token-transfers
Tx receive HMT token on Human-Protocol chain:
https://wan-red-ain.explorer.mainnet.skalenodes.com/tx/
0x0b516ec1ad438d2ac28c0924ff7e075b4d93968c762410a642b74042c9f51a
85/token-transfers


Thanks

**Comment by foufrix** [comment]
Hi @AzizBardi thanks for the contribution, @portuu3 is there all you need ?
One thing @AzizBardi this PR https://github.com/humanprotocol/hmt-escrow/pull/451 should be reported to this repo: https://github.com/humanprotocol/human-protocol as hmt-escrow has been migrated and the repo you commit to is deprecated

**Comment by AzizBardi** [comment]
@foufrix  i will do the necessary changes in the new repo but I thought the hmt escrow is the repo I am working on. will merge the pull request to the other repo :)

**Comment by portuu3** [comment]
@AzizBardi let me know when the PRs is ready and I will review

**Comment by AzizBardi** [comment]
> @AzizBardi let me know when the PRs is ready and I will review

PR is ready here https://github.com/humanprotocol/hmt-escrow/pull/451
But i will merge it to the other branch like foufrix mentioned

**Comment by portuu3** [comment]
> > @AzizBardi let me know when the PRs is ready and I will review
> 
> PR is ready here [humanprotocol/hmt-escrow#451](https://github.com/humanprotocol/hmt-escrow/pull/451) But i will merge it to the other branch like foufrix mentioned

I mean the PR in this repo https://github.com/humanprotocol/human-protocol

**Comment by AzizBardi** [comment]
@portuu3 https://github.com/humanprotocol/human-protocol/pull/259
pull request Done, looking forward to the approval and to talking with you !😃

**Comment by AzizBardi** [comment]
@foufrix @portuu3 pull request done ! :D
https://github.com/humanprotocol/human-protocol/pull/259

Looking forward for the approval ! 🙋🏻‍♂️🥳

**Comment by foufrix** [comment]
@AzizBardi portuu is currently in vacactions and will get back to you when he gets back 🙏

**Comment by AzizBardi** [comment]
> @AzizBardi portuu is currently in vacactions and will get back to you when he gets back 🙏 

Do you have an idea when he will gets back ?

**Comment by AzizBardi** [comment]
@foufrix @portuu3 this is an updated pull request (cleaner version)
https://github.com/humanprotocol/human-protocol/pull/287
thanks

**Comment by AzizBardi** [comment]
Hello @posix4e @portuu3 PR was merged, i just want to know what is next now ? :)
