### ISSUE TITLE
Add Neonlabs EVM and become the official maintainer for this network integration

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#140]
Human Protocol supports arbitrary EVM networks but there's a bit of work to do to make a network first class and make sure that it works. All of our EVM network launches are payable in ETH and you can gain a yearly bonus by being our network sponsor. If you need support please join tech-discussions on the human protocol discord linked on hmt.ai.

### Steps to receive a bounty
- [ ] Suggest and have us authorize your bridging strategy. After all we need to bridge HMT over to the new network. Usually, we need to use an erc20-compatible approach.
- [ ] Deploy the contracts on testnet
- [ ] Verify the contracts on the testnet block scanner
- [ ] Make sure that everything is working on testnet
- [ ] Add the new deployed contracts addresses to this [list](https://github.com/humanprotocol/human-protocol/blob/main/CONTRACTS_LIST.md)
- [ ] Transfer ownership of testnet contracts
- [ ] Launch a working app on the network. The easiest one to get going is our example [fortune](https://github.com/humanprotocol/human-protocol/tree/main/packages/examples/fortune). Make a video of the functionality of the app working on the new network and link to relevant scanner transactions.
- [ ] Deploy the contracts on mainnet
- [ ] Verify the contracts on the mainnet block scanner
- [ ] Make sure that everything is working on mainnet
- [ ] Add the new deployed contracts addresses to this [list](https://github.com/humanprotocol/human-protocol/blob/main/CONTRACTS_LIST.md)
- [ ] Transfer ownership of mainnet contracts
- [ ] Create a subgraph with this [sdk](https://github.com/humanprotocol/human-protocol/tree/main/packages/sdk/typescript/subgraph)
- [ ] Add to [human dashboard](https://dashboard.humanprotocol.org)
- [ ] Request to become the maintainer for your EVM network. We will list you on our repo, give you an extra reward (generally around 1 ETH per year) and invite you to conferences. We will celebrate your name forever!
- [ ] Bridge HMT from Ethereum
- [ ] Verify bridging of tokens works and link to relevant scanner transactions.

### High level rules to make sure that you are doing this correctly
- [ ] We never want to create a mintable token. Your change should not change the total token supply from 1 billion
- [ ] When deploying production contracts use a dedicated wallet with a seed phrase you don't use anywhere else. You might be required to share it with us.

**Comment by Charlie85270** [comment]
Hey guys ! I can work on this one !

**Comment by Charlie85270** [comment]
I deployed the contracts on NeonLabs Devnet (testnet and mainnet are not availabe yet) : 

HMToken Address:  0x717317A02dF5339f2b4AfFD8082EF3F98645756f
Staking Proxy Address:  0xE765240958a91DF0cF878b8a4ED23D5FF8effFFe
Staking Implementation Address:  0x82964e9e7F31966B602Abc7B12e456a87203c26A
Escrow Factory Proxy Address:  0xBB4c263309F79f4ec43cF3Bb0351deEc7fe3dF61
Escrow Factory Implementation Address:  0x6A93366b725Cae9073556f34ac74Ba2cd3aE2C1c
KVStore Address:  0xcDBfB6DEc4BB37A7D989FD36Bf06f42Ab50792Dc
Reward Pool Proxy Address:  0x9f35CAB0BDeD2B756Ae7de82A9cc228155fe6430
Reward Pool Implementation Address:  0x28df749CB1878EaF39d40D2acA2677EF4632e7Dc
Reputation Proxy Address:  0xc6E9e235087B434089c6Af46251A368c803B1b42
Reputation Implementation Address:  0x3E53FE7024BcB4cA83c79b68929Aac375d7f4B48
