### ISSUE TITLE
Oracles Judge fortune quality

### ISSUE THREAD

**Issue by posix4e** [humanprotocol/human-protocol#147]
**Description**
We need to make sure fortune oracles, use the human protocol to properly record and rate fortunes. To start off, let's make sure they are at least rated.

**Motivation**
This will provide a more full featured end to end prototype

**Implementation details** 
- [ ] Change the tests more granular and easy to read
- [ ] Assure non unique fortunes fail at exchange oracle
- [ ] Assure non unique fortunes fail at recording oracle level
- [ ] Have reputation oracle rate the quality of the fortune with a simple fortune teller reputation system
- [ ] Checkout https://github.com/humanprotocol/human-protocol/pull/98 . Do we want any of this code for our recording oracle?

**Comment by ansaqib** [comment]
@eugenvoronov - Can you take this into account for V2 and create the respective issues into the correct sprint

**Comment by portuu3** [comment]
@ansaqib all of this has been taken into account in this workflow https://miro.com/app/board/uXjVMblsix8=/ . We can close this
