### ISSUE TITLE
Weak Password Policy

### ISSUE THREAD

**Issue by basit511** [humanprotocol/human-protocol#1527]
https://app.humanprotocol.org/ 

Description:
When I tried to create a new Account I wrote on the field of Email:[nolmopokku1@nedoz.com](mailto:nolmopokku1@nedoz.com) and in the next step, when the site ask you the password for the account I have write on that field same characters of my Email Modify first latter as a capital : [Nolmopokku1@nedoz.com](mailto:Nolmopokku1@nedoz.com)
Then, I click on "sign up" and the account was successfully created but I was surprised because I know and I saw that some sites, when you try to create an account for example, with the password: xxx and Email (same): xxx , the site normally tells you. "Password can contains the same letters/characters of the Username/Email!" 

Why? To avoid the risk of stealing/brute forcing password. (For example, by seeing the "Username/Email" of the victim!) 

Note: Yes, is the question that some users asked "How anyone can know what's your password"..This is only an important practice that some important sites adopt to reduce the risk of the password stealing and I think that a site like forage should consider it. 

As I told you, this is a password policy issue..("Password can contains etc boablaba"), you can check it here: " http://www.comptechdoc.org/independent/security/policies/password-policy.html " 

See the 16 point of "4.0 Password Protection" section: "Don't use part of your login Email/name in your password. " 

In some cases..by considering these words: "Don't use part of your login Email/name in your password." some users decided independently to choose a password with the same characters of the Email/username "..but I think that, normally a site has to "tells and advertise" them that it's recommended to use a different password from the Email/username! 

My point is that some time it not depends from you the user choice but I think that by telling them the right way to choose, is the best solution

**Comment by Dzeranov** [comment]
Not relevant for this repo
