### ISSUE TITLE
Fortune Recording Oracle - Get data from manifest

### ISSUE THREAD

**Issue by eugenvoronov** [humanprotocol/human-protocol#163]
**Description**
Develop a client to retrieve data from the manifest.

**Motivation**
We want to develop a client that would be able to receive data from the manifests presented in the escrow in the `manifestUrl` parameter.

**Implementation details** 
- [x] Develop a client to retrieve data from the manifest

**Comment by eugenvoronov** [comment]
In current implementation `event IntermediateStorage(url, hash)` has required hash parameter. Should we send non-encrypted data there? Anyway events cannot be edit, does we need to store hash there? Maybe it makes more sense to hash the data itself to preserve its integrity? @posix4e

**Comment by posix4e** [comment]
The hash is a hash of the unecrypted data. The url can point to encrypted / unencrypted
