### ISSUE TITLE
Fortune Recording Oracle - Integration with Exchange Oracle

### ISSUE THREAD

**Issue by eugenvoronov** [humanprotocol/human-protocol#164]
**Description**
Develop a method of integration with Exchange Oracle.

**Motivation**
We would like to make Exchange Oracle and Recording Oracle work together using HTTP method.

**Implementation details** 
- [x] Develop a public controller without authorization
- [x] Process the response input received from the Exchange Oracle (uniqueness, curses-free)
- [x] Save the `teller` answer to local storage
- [x] Save the `teller` answer to s3 bucker JSON file and receive `url` to the JSON file
- [x] Get encrypted JSON file `data` as sha256 `hash`
- [x] Emit `IntermediateStorage(url, hash)`event in an escrow contract
- [x] Trigger Reputation Oracle and send answers in current chunk, if the `chunk` size is reached. Size of chunk is 5 by default.

**Comment by posix4e** [comment]
For 164 "Trigger Reputation Oracle if all answers are received" I think trigger reputation oracle every chunk. where chunk is a configurable amount of answers. By default set to 5

**Comment by posix4e** [comment]
I don't think the url needs to be encrypted since the data can be optionally encrypted
