### ISSUE TITLE
Fortune Recording Oracle - Integration with Reputation Oracle

### ISSUE THREAD

**Issue by eugenvoronov** [humanprotocol/human-protocol#165]
**Description**
Develop an api client to communicate with Reputation Oracle.

**Motivation**
When the job is fully completed, Recording Oracle should be able to send a request to Reputation Oracle to start calculating reputation points for `tellers`.

**Implementation details** 
- [x] Develop an api client to communicate with Reputation Oracle

**Comment by posix4e** [comment]
Since the recording oracle already has to write the data to steady storage. It can just provide a notification to the reputation oracle that there's data to fetch from a URL
