### ISSUE TITLE
Escrow Dashboard - Staking dashboard/tool

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#170]
**Description**
Staking dashboard to allow users to stake and choose the role they want to play within the protocol.

**Motivation**
Need of having a user friendly way for staking

**Implementation details** 
- [ ] Network selector: according to the selected network use the staking contract address for this network
- [ ] Stake: input amount
- [ ] Dashboard that shows staked and allocated amounts
- [ ] Unstake: input amount. Only available if has unallocated staking.
- [ ] Set role using kvStore (Job Launcher, Exchange Oracle, Recording Oracle, Reputation Oracle)
- [ ] Show accrued rewards
- [ ] Withdraw rewards
- [ ] Slash

**Comment by posix4e** [comment]
I like this

**Comment by eugenvoronov** [comment]
@portuu3 
It might help https://miro.com/app/board/uXjVPG1mXJc=/?moveToWidget=3458764537804136449&cot=14

**Comment by portuu3** [comment]
broken down into smaller tasks
