### ISSUE TITLE
[Reputation Oracle] Register hcaptcha labeler endpoint and store site keys

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#1899]
**Description**
1. Implement an endpoint which will register user as a labeler on hcaptcha services.
To be able to register himself as a labeler, user must be KYCed and have a record about that in KVStore.
Reference implementation: https://github.com/humanprotocol/human-app-backend/blob/38a03609f05fed4e047515d91e61fa16dd729210/src/app/hcaptchaLabeling/controller.js#L37

2. Add a site_keys database table to store hcaptcha site keys related to each user. In the begining this is only going to be used for hCaptcha, but should be extendable in case it is needed in the future

**Motivation**
We need to store hcaptcha site keys

**Implementation details** 
Table fields:
- Type: for now only hCaptcha
- Value
- UserId

1 to 1 relationship with Users table.
Load sitekey when getting users from the database

**Comment by eugenvoronov** [comment]
Create hCaptcha integration module
