### ISSUE TITLE
Analyze how to provide user/address statistics

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#216]
**Description**
Analyze how to provide user/address statistics and data:
- Number of escrows solved
- Grants amount
- Escrows solved paid
- ...

**Motivation**
Show the users their results

Note: we might need to add some event to the contract and add to subgraph

**Comment by flopez7** [comment]
1. Add workers and price lists in BulkTransfer event
2. Add worker's address in IntermediateStorage event
3. Create a new user schema with the following properties:
    - EscrowsSolved
    - GrantAmount
    - EscrowSolvedPaid
4. Modify event handlers to update the data in this new schema
