### ISSUE TITLE
Create Goerli subgraph on The Graph decentralized network

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#219]
**Description**
Create Goerli subgraph on The Graph decentralized network

**Motivation**
The graph will stop hosted services

**Implementation details** 
[How it should be done.](https://thegraph.com/docs/en/deploying/deploying-a-subgraph-to-studio/)

**Comment by flopez7** [comment]
Steps:
1. Create a subgraph in [Subgraph Studio](https://thegraph.com/studio/)
2. `npx graph auth --studio <DEPLOY KEY>`
3. `npx cross-env NETWORK=[NETWORK] yarn generate`
4. `npx graph deploy --studio < SUBGRAPH_SLUG >`
