### ISSUE TITLE
Deploy contracts with proxies on Avalanche mainnet & testnet

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#235]
**Description**
Deploy contracts new version of contracts (main branch) on Avalanche Mainnet and Testnet
Check this PR as an [example](https://github.com/humanprotocol/human-protocol/pull/228)

**Motivation**
Release new version of contracts with staking

**Implementation details** 
- [ ] Deploy contracts
- [ ] Verify contracts
- [ ] Update contracts list
- [ ] Deploy subgraph

**Comment by hrik2001** [comment]
Hi @portuu3, I was working on getting the contracts deployed. (Feel free to assign me this issue)
For deploying the contracts, needed to make sure what the parameters should be for initialization.

`Staking.sol` asks for
- `_token`: the HMToken address I believe
- `_minimumStake`: don't know what this value should be
- `_lockPeriod`: also don't know what this value should be

`EscrowFactory.sol` asks for
- `_staking`: the `Staking.sol`'s proxy address I believe

`Reward.sol` asks for
- `_token`: address for HMToken I believe
- `_staking`: the `Staking.sol`'s proxy address I believe
- `_fees`: I don't know what this value should be

**Comment by foufrix** [comment]
Any news on this issue @portuu3 @hrik2001

**Comment by portuu3** [comment]
> 
> `Staking.sol` asks for
> 
> * `_token`: the HMToken address I believe --> Yes
> * `_minimumStake`: don't know what this value should be --> 1
> * `_lockPeriod`: also don't know what this value should be --> 1
> 
> `EscrowFactory.sol` asks for
> 
> * `_staking`: the `Staking.sol`'s proxy address I believe --> Yes
> 
> `Reward.sol` asks for
> 
> * `_token`: address for HMToken I believe --> Yes
> * `_staking`: the `Staking.sol`'s proxy address I believe --> Yes
> * `_fees`: I don't know what this value should be --> 1

@hrik2001 answers above. 
You can use deploy-proxies.ts script

**Comment by foufrix** [comment]
Hi @hrik2001 any news about that ?

**Comment by hrik2001** [comment]
Hey, I am down for this. Do I have to apply again via gitcoin or do you want me to be assigned on this from github itself?

**Comment by foufrix** [comment]
Hi @hrik2001 any news on this? Do you need something from Human Protocol to advance on that?

**Comment by ansaqib** [comment]
@foufrix and @hrik2001 This issue has been closed internally
