### ISSUE TITLE
[Job Launcher] Get oracles endpoint

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#2353]
**Description**
Create an endpoint to fetch the list of available oracles 

**Motivation**
The users should be allowed to choose the oracles desired from this list

**Implementation details** 
Params:
- Job type
- Reputation Oracle address

Return an object like:
```
{
  "exchange_oracles": [ "address1", "address2"],
  "recording_oracles": [ "address1", "address2"]
}
```

**_Check how the list of exchange oracles is obtained in HUMAN APP_**

UPD:
`getReputationNetworkOperators` will be used, it will return IOperator with all necessary data.
```typescript
getReputationNetworkOperators(
    chainId: ChainId,
    address: string,
    role?: string
  ): Promise<IOperator[]>;

interface IOperator {
  address: string;
  role?: string;
  url?: string;
  jobTypes?: string[];
}
```

**Comment by eugenvoronov** [comment]
In this request the user does not specify the chain ID, make a request for all available chains on the launcher?

**Comment by portuu3** [comment]
Let's pass the chainId as param also
