### ISSUE TITLE
Load leaderboard from KVStore data

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#241]
**Description**
In the leaderboard must appear the users that have a key "role" in the kvstore

**Motivation**
Show leaderboard information

**Implementation details** 
Use this query to get from subgraph the roles. Have in mind that the same user may have more than event for key "role" so we need to take only the last one. (leader is the address)
```
{dataSavedEvents(where: { key: "role"} ) {
    leader
    key
    value
    timestamp
  }
}
```

Get staking amount from staking contract using function `getStakedTokens`

**Comment by m00n620** [comment]
I double-checked, and @leric7 pushed a commit in `feat/wallet-connect` branch to load leaderboard data from kvstore. I think we can close this issue, @portuu3

**Comment by m00n620** [comment]
@portuu3 , however could you please let me know how to use kvstore for testing purpose?
