### ISSUE TITLE
[Human App] Add throttling to the refresh button

### ISSUE THREAD

**Issue by Dzeranov** [humanprotocol/human-protocol#2795]
**Description**
Need to add throttling mechanism to the refresh button:
![image](https://github.com/user-attachments/assets/112739d2-58ec-4f7c-aa63-7b32ada42719)

**Motivation**
To avoid spamming requests to the exchange oracle.

**Comment by dnechay** [comment]
In the future we might want to add api rate limiter to corresponding endpoint if it becomes an issue, but now having just "loading" state should be fine
