### ISSUE TITLE
[HUMAN App] Create an Endpoint to Fetch Enabled Networks

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#2830]
**Description**
Develop a new API endpoint that returns the list of enabled networks.

**Motivation**
Allow the frontend to dynamically fetch the list of enabled networks to ensure consistency between the frontend and backend configuration.

**Implementation details** 
	•	Create a new ConfigController.
	•	Add an endpoint (e.g., GET /config/networks) to the controller.
	•	Ensure the endpoint returns the list of enabled networks as defined in the backend configuration.
	•	Add appropriate unit tests to validate the functionality.

**Comment by dnechay** [comment]
Are we going to have an endpoint specifically for chains config? Maybe have just one `/config` that can be used to load full configuration when app loads?

Do we plan to cleanup changes introduced in https://github.com/humanprotocol/human-protocol/pull/2816 &  https://github.com/humanprotocol/human-protocol/pull/2819 as part of this issue?
