### ISSUE TITLE
Job Launcher - Get liquidity data from subgraph

### ISSUE THREAD

**Issue by eugenvoronov** [humanprotocol/human-protocol#296]
**Description**
Implement subgraph support to get liquidity.

**Motivation**
Getting networks with the most liquidity will allow the requester to evaluate the popularity of the network, and submit jobs in networks with the most employees and the lowest cost per job.

**Implementation details** 
Create an HTTP method that would fetch liquidity data and return it to the user.
**GET** `<HOST>/liquidity`

**Comment by s7c** [comment]
ACCEPTANCE CRITERIA:

1. Ensure that the implemented subgraph collects and process the data flawlessly.
2. Update relevant documentation to include the new details
