### ISSUE TITLE
Fortune V2 - Implement `typescript SDK` instead of using the contracts interface

### ISSUE THREAD

**Issue by eugenvoronov** [humanprotocol/human-protocol#309]
**Description**
Using SDK instead of `JSON` file contract interfaces.

**Motivation**
Using the latest versions of the contract. Using SDK instead of JSON files.

**Implementation details** 
Implement [typescript SDK](https://github.com/humanprotocol/human-protocol/tree/main/packages/sdk/typescript/human-protocol-sdk).

**Comment by portuu3** [comment]
Done
