### ISSUE TITLE
Fix staking contract - add total slashing amount validation

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#376]
**Description**
Check that the sum of the new slash and existing slashes, is not higher than the allocation of the escrow.

**Motivation**
Validate that the slash can be done

**Implementation details** 
Add the validation in the slash function of staking contract

**Comment by leric7** [comment]
@portuu3 , we don't track existing slashes on-chain. Each time we slash, allocation is cut out, so I'd say we already have this mechanism.

**Comment by leric7** [comment]
BTW, I think it's worth adding test case for this scenario, so that we can ensure we have this mechanism correctly implemented.
