### ISSUE TITLE
Fix tokensLockedUntil in staking contract

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#377]
**Description**
If we unallocate from an escrow A and then from another escrow B, the lock period for both unallocated amount of tokens will be the locking period of escrow B.

**Motivation**
We should be able to unlock the tokens from each escrow with a different date

**Implementation details** 
An option might be to move the variable tokensLockedUntil to the allocation struct

**Comment by leric7** [comment]
@portuu3 , AFAIK token lock is only applied to unstaking tokens, not for closing allocations from escrows.
