### ISSUE TITLE
Job Launcher Server - database

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#475]
**Description**
Design database and create migration scripts

**Implementation details** 
**Tables:**
- Auth
- Token
- User
- Jobs
- Payments

**Comment by eugenvoronov** [comment]
https://www.notion.so/human-protocol/Job-Launcher-fdd11e3261de4d95b5c8a8477f9ef6a9?pvs=4#ea84c1d32dcb4e17b5a02ed68e558694
