### ISSUE TITLE
Dashboard supports escrow factory upgrade

### ISSUE THREAD

**Issue by m00n620** [humanprotocol/human-protocol#54]
@portuu3 , we should support escrow factory upgrades in the dashboard.

Please work on smart contract & subgraph for this task as we discussed yesterday and let me know once it's ready to be integrated on frontend.

Also currently we are missing a lot of escrow factories that we previously ran. Let's track down all of the Escrow factories that Intuition Machines has ever run (ethereum ropsten/polygon dev net) and make sure they are on the dashboard

**Comment by portuu3** [comment]
@m00n620 you can find the data for Rinkeby network [here](https://github.com/humanprotocol/human-protocol/tree/main/packages/apps/escrow-dashboard/history-data)
