### ISSUE TITLE
SDK - Upgrade ethers version to v6 in SDK

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#605]
**Description**
Update the library used to interact with blockchain in typescript to the latest version

**Implementation details**
Update ethers to the latest library version 
Update all the ethers dependant libraries to use the new v6 format (like typechain, hardhat, ...)
Update all the SDK dependant projects in monorepo to use the new SDK

**Comment by s7c** [comment]
Acceptance criteria: 

1. Verify that the updates does not introduce breaking changes to existing functionalities.
2. Libraries such as typechain, hardhat, and any other libraries relying on ethers are tested to ensure compatibility with the latest version.
3. Verify by testing it that the updated SDK version does not introduce compatibility issues with existing projects and works as expected.
4. Update the proper documentation with the changes that you made & evaluate the performance impact of the library updates, particularly in terms of execution speed and resource usage.
