### ISSUE TITLE
Eth kv store webapp

### ISSUE THREAD

**Issue by posix4e** [humanprotocol/human-protocol#64]
- [ ] Allow for arbitary get/set tab
- [ ] Decrypt should allow you to specify a private key to decrypt with and take in a cipher text message
- [ ] Encrypt should take in an address, and a plain text message and produce cipher text
- [ ] Your public key, should just display your public key from what's stored in eth kv store

**Comment by spiritupbro** [comment]
hello i want to ask is this the same app as eth kv store web gui? but you wanted to put it inside here?

**Comment by ansaqib** [comment]
Hey @spiritupbro - We have moved to a monorepo structure and you can find it https://github.com/humanprotocol/human-protocol/tree/main/packages/examples/eth-kvstore-gui

**Comment by spiritupbro** [comment]
@ansaqib thanks for the answer, i think i need to rephrasd my question, i see that its completely different than my app, so where should i put this new app? should i add new route like `/kvstore` and follow the design style of this repo?

**Comment by ansaqib** [comment]
The fastest is to have a call. Please book my time here (https://calendly.com/saqib-hmt)
