### ISSUE TITLE
Job Launcher - Negative balance constraint

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#744]
**Description**
Add a constraint in payments table to avoid negative balances.

**Motivation**
It is a security issue, the balance cannot be negative.

**Implementation details** 
Check if convert the data type to decimal allows to do the calculation or find any other solution.

**Comment by eugenvoronov** [comment]
Waiting for comments from @Dzeranov about balances and general improvements. Based on these comments related with integration of balance improvements, this PR will be updated and closed.

**Comment by eugenvoronov** [comment]
Please, don't delete fix/launcher-balances branch. Current PR will be redone and reopened.
