### ISSUE TITLE
Update to reputation algorithm to include data quality measures.

### ISSUE THREAD

**Issue by simulacrum6** [humanprotocol/human-protocol#779]
**Is your feature request related to a problem? Please describe.**
The current iteration of the reputation algorithm is fairly simple and limited. It updates only Recording Oracles, not workers and does not account for the quality of the Job's results (i.e. data).

**Describe the solution you'd like**
Design an updated algorithm / algorithms that takes data quality into account and updates workers and recording oracles alike.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by s7c** [comment]
ACCEPTANCE CRITERIA: 
1. The algorithm's data quality metric should align with the platform's standards and user expectations.
2. The algorithm should efficiently handle a growing number of workers and recording oracles without compromising system performance.
3. Define and document the rationale behind the algorithm strategy and implementation.
