### ISSUE TITLE
[Job Launcher] Any transaction with right parameters can deposit balance

### ISSUE THREAD

**Issue by eugenvoronov** [humanprotocol/human-protocol#940]
**Bug description**
When a user attempts to deposit their balance using cryptocurrency, they are required to provide a transaction hash as a parameter for the `POST /payment/crypto` endpoint. However, within the `createCryptoPayment` method, there is currently no validation in place to verify the authenticity of the transaction or its age.

**Expected behaviour**
The service should only grant access to the transaction if it meets certain validity criteria. This may include verifying that the transaction was initiated by the Job Requester and ensuring that the transaction is not too old to be considered valid.

**Comment by ansaqib** [comment]
Duplicated into Q4 issue #953
